### ISSUE TITLE
Lots of broken links (to github) on "Using Kong for Kubernetes Enterprise" page

### ISSUE THREAD

**Issue by vaughnbuttiw** [Kong/docs.konghq.com#3176] opened 2021-09-02 20:03 UTC
### Where is the problem?

https://docs.konghq.com/enterprise/2.5.x/deployment/using-kong-for-kubernetes/

### What happened?

There are some (many? all?) links on the page https://docs.konghq.com/enterprise/2.5.x/deployment/using-kong-for-kubernetes/ to github that are broken (404).

Examples:
* https://github.com/Kong/kubernetes-ingress-controller/tree/main/docs
* https://github.com/Kong/kubernetes-ingress-controller/blob/main/docs/concepts/design.md
* https://github.com/Kong/kubernetes-ingress-controller/blob/main/docs/concepts/custom-resources.md
* https://github.com/Kong/kubernetes-ingress-controller/blob/main/docs/concepts/ha-and-scaling.md

### What did you expect to happen?

I expected to be able to see the relevant documentation when I clicked on the links on the page.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by lena-larionova** [comment] 2021-09-02 23:47
@vaughnbuttiw Thanks for reporting this. Turns out there was a bigger issue at work: this page is a duplicate of https://docs.konghq.com/kubernetes-ingress-controller/ and shouldn't exist anymore. I did a pass over the rest of the docs as well to catch any remaining links to the old repo.

**Comment by vaughnbuttiw** [comment] 2021-09-02 23:53
I think that removing the page https://docs.konghq.com/enterprise/2.5.x/deployment/using-kong-for-kubernetes/ is an acceptable solution. Because it is a duplicate. And a duplicate in, at best, an odd place.

**Closed** 2021-09-08 17:17 UTC
