### ISSUE TITLE
Issue when viewing pages on a portrait mode monitor.

### ISSUE THREAD

**Issue by rkazak** [Kong/docs.konghq.com#3445] opened 2021-12-01 20:51 UTC
### Where is the problem?

When I look at this page - https://docs.konghq.com/konnect-platform/plans/#plan-comparison on my portrait monitor I see the following embedded markup(?)

![Screen Shot 2021-12-01 at 12 49 02 PM](https://user-images.githubusercontent.com/3156268/144311686-20a5d08e-423c-4116-973b-8ae051e086a9.png)

But on my laptop monitor in landscape mode it appears as expected?

### What is your suggestion?

Not sure what tools are being used, but suggest, if not already doing so, testing on both landscape and portrait mode monitors?

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by lena-larionova** [comment] 2021-12-01 21:28
@rkazak can you refresh the page and see if it still happens?

**Comment by lena-larionova** [comment] 2021-12-03 00:07
We have removed this page, as it is a duplicate of https://konghq.com/pricing/. 

I couldn't reproduce the issue either with mobile or by resizing pages. If you run into it again on another page, please open another issue.

**Closed by lena-larionova** 2021-12-03 00:07 UTC
