### ISSUE TITLE
Kong performance testing framework

### ISSUE THREAD

**Issue by 11megha123** [Kong/docs.konghq.com#3931] opened 2022-05-12 14:41 UTC
### Where is the problem?

Hi team,
I am trying to test the sample script for kong performance framework given on below link:
https://docs.konghq.com/gateway/latest/plan-and-deploy/performance-testing-framework/

But while executing the script , getting below error:
20:05:40.768   [warn] [controller] failed in start_upstreams: failed to start nginx: process exited with code 1: exit: , tries: 1
20:05:40.793   [warn] [controller] failed in start_upstreams: failed to start nginx: process exited with code 1: exit: , tries: 2
20:05:40.814   [warn] [controller] failed in start_upstreams: failed to start nginx: process exited with code 1: exit: , tries: 3

Error → spec/optmisation/test_sample_spec.lua @ 10
perf test for Kong git:master #simple #no_plugins lazy_setup
./spec/helpers/perf.lua:116: start_upstreams finally failed after 3 tries

upstream port and url is changed in script

Please help.

Also -  pls explain
what to write in this section 
before_each(function()
      perf.start_kong(version, {
        --kong configs
      })
    end)
kong configs of the script

### What is your suggestion?

script sud be executed

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by mheap** [comment] 2022-08-05 10:36
Duplicate of 3923

**Closed by mheap** 2022-08-05 10:36 UTC
